// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameItemsToitemCategory = "_ItemsToitem_category"

// ItemsToitemCategory mapped from table <_ItemsToitem_category>
type ItemsToitemCategory struct {
	A int32 `gorm:"column:A;not null" json:"A"`
	B int32 `gorm:"column:B;not null" json:"B"`
}

// TableName ItemsToitemCategory's table name
func (*ItemsToitemCategory) TableName() string {
	return TableNameItemsToitemCategory
}
