// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameItemsTostoreLocation = "_ItemsTostore_location"

// ItemsTostoreLocation mapped from table <_ItemsTostore_location>
type ItemsTostoreLocation struct {
	B int64 `gorm:"column:B;not null" json:"B"`
	A int64 `gorm:"column:A;not null" json:"A"`
}

// TableName ItemsTostoreLocation's table name
func (*ItemsTostoreLocation) TableName() string {
	return TableNameItemsTostoreLocation
}
