// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAddress = "Address"

// Address mapped from table <Address>
type Address struct {
	ID                           int32  `gorm:"column:id;primaryKey" json:"id"`
	AddressLine1                 string `gorm:"column:address_line_1" json:"address_line_1"`
	AddressLine2                 string `gorm:"column:address_line_2" json:"address_line_2"`
	Locality                     string `gorm:"column:locality" json:"locality"`
	AdministrativeDistrictLevel1 string `gorm:"column:administrative_district_level_1" json:"administrative_district_level_1"`
	PostalCode                   string `gorm:"column:postal_code" json:"postal_code"`
	Country                      string `gorm:"column:country" json:"country"`
}

// TableName Address's table name
func (*Address) TableName() string {
	return TableNameAddress
}
