// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEmailCampaign = "EmailCampaign"

// EmailCampaign mapped from table <EmailCampaign>
type EmailCampaign struct {
	ID           int32  `gorm:"column:id;primaryKey" json:"id"`
	TargetEmails string `gorm:"column:target_emails" json:"target_emails"`
	From         string `gorm:"column:from;not null" json:"from"`
	SendTime     string `gorm:"column:send_time;not null" json:"send_time"`
	Subject      string `gorm:"column:subject;not null" json:"subject"`
	Text         string `gorm:"column:text;not null" json:"text"`
	HTML         string `gorm:"column:html;not null" json:"html"`
	CampaignID   int32  `gorm:"column:campaignId;not null" json:"campaignId"`
}

// TableName EmailCampaign's table name
func (*EmailCampaign) TableName() string {
	return TableNameEmailCampaign
}
