// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFbAd = "fb_ad"

// FbAd mapped from table <fb_ad>
type FbAd struct {
	ID           int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FbAdsetID    string `gorm:"column:fb_adset_id;not null" json:"fb_adset_id"`
	Name         string `gorm:"column:name;not null" json:"name"`
	Creative     string `gorm:"column:creative;not null" json:"creative"`
	Status       string `gorm:"column:status;not null" json:"status"`
	FbCampaignID int32  `gorm:"column:fb_campaignId" json:"fb_campaignId"`
}

// TableName FbAd's table name
func (*FbAd) TableName() string {
	return TableNameFbAd
}
