// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGeoLocation = "geo_locations"

// GeoLocation mapped from table <geo_locations>
type GeoLocation struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Countries  string `gorm:"column:countries" json:"countries"`
	Regions    string `gorm:"column:regions" json:"regions"`
	Cities     string `gorm:"column:cities" json:"cities"`
	ZipCodes   string `gorm:"column:zip_codes" json:"zip_codes"`
	FbTargetID int32  `gorm:"column:fb_targetId;not null" json:"fb_targetId"`
}

// TableName GeoLocation's table name
func (*GeoLocation) TableName() string {
	return TableNameGeoLocation
}
