// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameItem = "Items"

// Item mapped from table <Items>
type Item struct {
	Type                  string `gorm:"column:type;not null" json:"type"`
	UpdatedAt             string `gorm:"column:updated_at;not null" json:"updated_at"`
	CreatedAt             string `gorm:"column:created_at;not null" json:"created_at"`
	PresentAtAllLocations bool   `gorm:"column:present_at_all_locations;not null" json:"present_at_all_locations"`
	Name                  string `gorm:"column:name;not null" json:"name"`
	Description           string `gorm:"column:description;not null" json:"description"`
	ProductType           string `gorm:"column:product_type;not null" json:"product_type"`
	PurchaseID            int64  `gorm:"column:purchaseId" json:"purchaseId"`
	OrganizationID        int64  `gorm:"column:organizationId;not null" json:"organizationId"`
	IsDeleted             bool   `gorm:"column:isDeleted;not null" json:"isDeleted"`
	ItemID                string `gorm:"column:item_id;not null" json:"item_id"`
	ID                    int64  `gorm:"column:id;primaryKey" json:"id"`
	CategoryID            string `gorm:"column:category_id" json:"category_id"`
}

// TableName Item's table name
func (*Item) TableName() string {
	return TableNameItem
}
