// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrganization = "Organization"

// Organization mapped from table <Organization>
type Organization struct {
	ID                int32     `gorm:"column:id;primaryKey" json:"id"`
	Name              string    `gorm:"column:name;not null" json:"name"`
	CreatedAt         time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	FbCustomAudiences string    `gorm:"column:fb_custom_audiences" json:"fb_custom_audiences"`
	IsSendgridAuthed  bool      `gorm:"column:is_sendgrid_authed;not null" json:"is_sendgrid_authed"`
	IsTwilioAuthed    bool      `gorm:"column:is_twilio_authed;not null" json:"is_twilio_authed"`
	Plan              int32     `gorm:"column:plan;not null" json:"plan"`
	PosID             int32     `gorm:"column:posId;not null" json:"posId"`
	SendgridEmail     string    `gorm:"column:sendgrid_email;not null" json:"sendgrid_email"`
	TwilioNumber      string    `gorm:"column:twilio_number;not null" json:"twilio_number"`
	Type              string    `gorm:"column:type;not null" json:"type"`
	UpdatedAt         time.Time `gorm:"column:updatedAt;not null;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName Organization's table name
func (*Organization) TableName() string {
	return TableNameOrganization
}
