// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePo = "Pos"

// Po mapped from table <Pos>
type Pos struct {
	ID             int64     `gorm:"column:id;primaryKey" json:"id"`
	Name           string    `gorm:"column:name;not null" json:"name"`
	AccessToken    string    `gorm:"column:access_token;not null" json:"access_token"`
	RefreshToken   string    `gorm:"column:refresh_token;not null" json:"refresh_token"`
	ExpiresAt      time.Time `gorm:"column:expires_at;not null" json:"expires_at"`
	MerchantID     string    `gorm:"column:merchant_id;not null" json:"merchant_id"`
	OrganizationID int64     `gorm:"column:organizationId;not null" json:"organizationId"`
}

// TableName Po's table name
func (*Pos) TableName() string {
	return TableNamePo
}
