// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStoreLocation = "store_location"

// StoreLocation mapped from table <store_location>
type StoreLocation struct {
	ID                           int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name                         string `gorm:"column:name;not null" json:"name"`
	AddressLine1                 string `gorm:"column:address_line_1;not null" json:"address_line_1"`
	Locality                     string `gorm:"column:locality;not null" json:"locality"`
	AdministrativeDistrictLevel1 string `gorm:"column:administrative_district_level_1;not null" json:"administrative_district_level_1"`
	PostalCode                   string `gorm:"column:postal_code;not null" json:"postal_code"`
	Country                      string `gorm:"column:country;not null" json:"country"`
	Timezone                     string `gorm:"column:timezone;not null" json:"timezone"`
	Capabilities                 string `gorm:"column:capabilities" json:"capabilities"`
	Status                       string `gorm:"column:status;not null" json:"status"`
	CreatedAt                    string `gorm:"column:created_at;not null" json:"created_at"`
	MerchantID                   string `gorm:"column:merchant_id;not null" json:"merchant_id"`
	LanguageCode                 string `gorm:"column:language_code;not null" json:"language_code"`
	Currency                     string `gorm:"column:currency;not null" json:"currency"`
	PhoneNumber                  string `gorm:"column:phone_number" json:"phone_number"`
	BusinessName                 string `gorm:"column:business_name;not null" json:"business_name"`
	OrganizationID               int64  `gorm:"column:organizationId;not null" json:"organizationId"`
	PosID                        string `gorm:"column:pos_id;not null" json:"pos_id"`
	Type                         string `gorm:"column:type" json:"type"`
}

// TableName StoreLocation's table name
func (*StoreLocation) TableName() string {
	return TableNameStoreLocation
}
