// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/lib/pq"

const TableNameTextCampaign = "text_campaign"

// TextCampaign mapped from table <text_campaign>
type TextCampaign struct {
	ID            int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TargetNumbers pq.StringArray `gorm:"type:varchar(255)[]" json:"target_numbers"`
	From          string `gorm:"column:from;not null" json:"from"`
	SendTime      string `gorm:"column:send_time;not null" json:"send_time"`
	Body          string `gorm:"column:body;not null" json:"body"`
	CampaignID    int32  `gorm:"column:campaignId;not null" json:"campaignId"`
	Name 		string `gorm:"column:name;not null" json:"name"`
}

// TableName TextCampaign's table name
func (*TextCampaign) TableName() string {
	return TableNameTextCampaign
}
