// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "User"

// OrganizationToUser table looks like this:
// CREATE TABLE _OrganizationToUser (
//     A int4 NOT NULL,
//     B int4 NOT NULL,
//     CONSTRAINT _OrganizationToUser_pkey PRIMARY KEY (A, B)
// );
// User mapped from table <User>
type User struct {
	ID        int64     `gorm:"column:id;primaryKey" json:"id"`
	OrganizationID int64 `gorm:"column:organizationId;not null" json:"organizationId"`
	Email     string    `gorm:"column:email;not null" json:"email"`
	FirstName string    `gorm:"column:firstName;not null" json:"firstName"`
	LastName  string    `gorm:"column:lastName;not null" json:"lastName"`
	CreatedAt time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	Password  string    `gorm:"column:password;not null" json:"password"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
