// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAdProvider = "ad_provider"

// AdProvider mapped from table <ad_provider>
type AdProvider struct {
	ID             int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name           string `gorm:"column:name;not null" json:"name"`
	IsAuthed       bool   `gorm:"column:is_authed;not null" json:"is_authed"`
	AccessToken    string `gorm:"column:access_token;not null" json:"access_token"`
	RefreshToken   string `gorm:"column:refresh_token;not null" json:"refresh_token"`
	OrganizationID int32  `gorm:"column:organizationId;not null" json:"organizationId"`
}

// TableName AdProvider's table name
func (*AdProvider) TableName() string {
	return TableNameAdProvider
}
