// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCustomerGroup = "customer_groups"

// CustomerGroup mapped from table <customer_groups>
type CustomerGroup struct {
	ID             int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name           string `gorm:"column:name;not null" json:"name"`
	CustomerID     string `gorm:"column:customer_id" json:"customer_id"`
	OrganizationID int32  `gorm:"column:organizationId;not null" json:"organizationId"`
}

// TableName CustomerGroup's table name
func (*CustomerGroup) TableName() string {
	return TableNameCustomerGroup
}
