// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "User"

// User mapped from table <User>
type User struct {
	ID        int32     `gorm:"column:id;primaryKey" json:"id"`
	Email     string    `gorm:"column:email;not null" json:"email"`
	FirstName string    `gorm:"column:firstName;not null" json:"firstName"`
	LastName  string    `gorm:"column:lastName;not null" json:"lastName"`
	CreatedAt time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	Password  string    `gorm:"column:password;not null" json:"password"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
