name: Deploy to ECR

on:
 
  push:
    branches: [ main ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Create env file
      run: |
        touch .env
        echo JWT_SECRET=${JWT_SECRET} > .env
        echo SENDGRID_API_KEY=${SENDGRID_API_KEY} > .env
        echo TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID} > .env
        echo TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN} > .env
        echo AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} > .env
        echo AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} > .env
        echo SENDINBLUE_API_KEY=${SENDINBLUE_API_KEY} > .env
        echo DB_URL=${DB_URL} > .env
        echo GATEWAY_URL=${GATEWAY_URL} > .env
        echo SHOPIFY_ARN=${SHOPIFY_ARN} > .env
        cat .env
      env: 
        JWT_SECRET: ${{ secrets.JWT_SECRET }} 
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }} 
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SENDINBLUE_API_KEY: ${{ secrets.SENDINBLUE_API_KEY }} 
        DB_URL: ${{ secrets.DB_URL }}
        GATEWAY_URL: ${{ secrets.GATEWAY_URL }} 
        SHOPIFY_ARN: ${{ secrets.SHOPIFY_ARN }}

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: nucleus-ecr
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
